apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d0ze17dug-python 
  janus-idp.io/tekton: d0ze17dug-python
  backstage.io/kubernetes-id: d0ze17dug-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d0ze17dug-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml